guideme/public/index.html
guideme/src/components/Cell/index.js
guideme/src/components/Gridx/index.js
guideme/src/components/Wrapper/index.js
guideme/src/components/Wrapper/style.css

Components added: Cell, Gridx, Wrapper
Pages added: Homepage

Ajb first merge

---

guideme/public/index.html
guideme/src/App.js
guideme/src/components/Card/index.js
guideme/src/components/Gridx/index.js
guideme/src/components/TopBar/index.js
guideme/src/components/TopBar/style.css
guideme/src/fakedb/adventures.json
guideme/src/fakedb/users.json
guideme/src/pages/Adventures/index.js

Added two json files for dev until db connection made
added Card component
added minimal styling to topBar

Mh first page

---

guideme/src/App.js
guideme/src/components/Card/index.js
guideme/src/components/FlipCard/index.js
guideme/src/components/FlipCard/style.css
guideme/src/fakedb/adventures.json
guideme/src/pages/Adventures/index.js

some styling and basic structure
linked to adventures.json

Mh adventures page

---

guideme/src/App.js
guideme/src/components/TopBar/index.js
guideme/src/components/TopBar/style.css
guideme/src/pages/Adventures/index.js
guideme/src/pages/Homepage/index.js
guideme/src/pages/NotFound/index.js
guideme/src/pages/Profile/index.js

topBar moved to App.js
User login and host states tracked
footer moved to App.js

App.js setup to integrate topbar

---

guideme/src/components/TagRow/index.js
guideme/src/components/TagRow/style.css
guideme/src/fakedb/users.json
guideme/src/pages/Homepage/index.js
guideme/src/pages/Profile/index.js
guideme/src/pages/Profile/style.css

Components loaded
Looks for host vs not host role

Mh profile page

---

guideme/src/App.js
guideme/src/components/Footer/index.js
guideme/src/components/Footer/style.css
guideme/src/components/Stickyfooter/index.js
guideme/src/components/Stickyfooter/style.css
guideme/src/components/TopBar/index.js
guideme/src/components/TopBar/style.css
guideme/src/components/Wrapper/style.css
guideme/src/pages/Homepage/index.js
guideme/src/pages/Homepage/style.css

Navbar edited, sticky footer edited. Responsive and mobile both look good with search feature.

Search on homepage added

---

guideme/package-lock.json
guideme/package.json
guideme/src/components/FlipCard/index.js
guideme/src/pages/Adventures/index.js
guideme/src/pages/Profile/index.js
guideme/src/util/API.js

get routes built and user + adventrue data populates

Mh api get

---

guideme/src/util/API.js

user and adventure post utils written
not yet tested!

Mh api post

---

guideme/public/index.html
guideme/src/App.js
guideme/src/components/Adventure/index.js
guideme/src/components/Btn/index.js
guideme/src/components/SignIn/index.js
guideme/src/components/SignUp/index.js
guideme/src/components/TagRow/index.js
guideme/src/pages/Adventures/index.js
guideme/src/pages/Login/index.js
guideme/src/pages/Profile/index.js
guideme/src/util/API.js

Sign in and sign up API connections established.
Profile page rendering conditional on sign in

Mh profile page vol2

---

guideme/package-lock.json
guideme/package.json
guideme/src/components/Adventure/index.js
guideme/src/components/Stickyfooter/index.js
guideme/src/pages/Adventures/index.js
guideme/src/pages/Homepage/index.js
guideme/src/pages/Profile/index.js

adventure component edited with all the inputs needed for host

Ism advent

---

guideme/src/App.js
guideme/src/components/Adventure/index.js
guideme/src/components/Btn/index.js
guideme/src/components/FlipCard/style.css
guideme/src/components/Wrapper/style.css
guideme/src/pages/Adventures/index.js
guideme/src/pages/Profile/index.js
guideme/src/pages/Profile/style.css
guideme/src/util/API.js

and other bits and bobs:
create adventure form integration etc.

Mh delete functionality

---

guideme/src/App.js
guideme/src/components/AdventureUpdate/index.js
guideme/src/components/UserUpdate/index.js
guideme/src/pages/Profile/index.js

reloads data on updates
deleted host state from app.js, don't really need it

Mh reload on updates

---

src/App.js
src/components/Adventure/index.js
src/components/AdventureUpdate/index.js
src/components/SignIn/index.js
src/components/UserUpdate/index.js
src/pages/Adventures/index.js
src/pages/Homepage/index.js
src/pages/Login/index.js
src/pages/NotFound/index.js
src/pages/Profile/index.js
src/util/API.js

search works,
host button toggle works,
most errors removed from console,
other little changes for tags and page name stuff etc

Mh error removal

---

src/components/Adventure/index.js
src/components/Form/style.css

Adventure update bug fix

---

src/components/Form/style.css
src/components/Messages/index.js
src/components/Stickyfooter/index.js
src/pages/Homepage/index.js
src/pages/Homepage/style.css
src/pages/Profile/index.js

e.preventStopProp added to adventure card update, className added to cells for update profile, create adventure, delete account

Input field text now white

---

src/App.js
src/components/LoginContext/index.js
src/components/SignIn/index.js

login state persistence fixed

---

src/App.js
src/components/Adventure/index.js
src/components/AdventureUpdate/index.js
src/components/FlipCard/index.js
src/components/SignIn/index.js
src/components/TagBox/index.js
src/components/TagBox/style.css
src/components/TagRow/index.js
src/components/TagRow/style.css
src/components/UserUpdate/index.js
src/pages/Adventures/index.js
src/pages/Profile/index.js

tags can now be added, deleted etc

Mh tag inputs

---

src/pages/Community/index.js

Two commits, fixing little snippets on reviews and community page posting,.

Mh demoday stuff

---

src/components/UserUpdate/index.js
src/components/ViewReview/index.js

- minor bug fixes and small improvements

Mh lastminute changes

---

src/components/Mailbox/index.js
src/components/Messages/index.js
src/components/PopupChat/index.js

live chat changes and auto scroll built in.

real time chat should now be working
